/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Activity */
        get: operations["system_activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authority Copy */
        get: operations["authority_copy_api_v1_copy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decisions */
        get: operations["decisions_api_v1_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decisions Grouped
         * @description The sidebar list: grouped, filtered and pinned exactly as the page does it.
         */
        get: operations["decisions_grouped_api_v1_decisions_grouped_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Lifecycle */
        get: operations["decision_lifecycle_api_v1_decisions__digest__lifecycle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Market */
        get: operations["decision_market_api_v1_decisions__digest__market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/memo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Memo */
        get: operations["decision_memo_api_v1_decisions__digest__memo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Outcomes */
        get: operations["decision_outcomes_api_v1_decisions__digest__outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Proof */
        get: operations["decision_proof_api_v1_decisions__digest__proof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Risk */
        get: operations["decision_risk_api_v1_decisions__digest__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Structure */
        get: operations["decision_structure_api_v1_decisions__digest__structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{digest}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Summary */
        get: operations["decision_summary_api_v1_decisions__digest__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents */
        get: operations["incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Overview
         * @description `CIIP-008`'s evidence, as counts. No rate is served because none is
         *     available: see `presentation/horizons.py`.
         */
        get: operations["review_overview_api_v1_outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proof/{digest}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proof File
         * @description The manifest as the exact bytes a reviewer keeps.
         *
         *     Deliberately not enveloped: wrapping would change the bytes and so the
         *     digest, and the digest is the thing a reviewer checks.
         */
        get: operations["proof_file_api_v1_proof__digest__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Proof */
        get: operations["system_proof_api_v1_system_proof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tour": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guided Tour */
        get: operations["guided_tour_api_v1_tour_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Worker Events */
        get: operations["worker_events_api_v1_worker_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountingOut */
        AccountingOut: {
            /** Account Equity */
            account_equity: string | null;
            /** Budget Used Percent */
            budget_used_percent: string | null;
            /** Maximum Loss */
            maximum_loss: string | null;
            /** Risk Budget */
            risk_budget: string | null;
        };
        /** ActivityEventOut */
        ActivityEventOut: {
            /** Component */
            component: string;
            /** Correlation Id */
            correlation_id: string;
            /** Occurred At */
            occurred_at: string | null;
            /** Outcome */
            outcome: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Refused */
            refused: boolean;
            /** Sequence */
            sequence: number;
            /** Stage */
            stage: string;
        };
        /** ActivityPage */
        ActivityPage: {
            /** Items */
            items: components["schemas"]["ActivityEventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ArtifactOut
         * @description A committed artifact and whether it belongs to this decision.
         */
        ArtifactOut: {
            /** Belongs */
            belongs: boolean;
            /** Facts */
            facts: {
                [key: string]: string | number | boolean | null;
            };
            /** Matched On */
            matched_on: string | null;
            /** Reason */
            reason: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "THIS_DECISION" | "OTHER_DECISION" | "NOT_DECISION_SCOPED" | "UNKNOWN";
        };
        /**
         * CopyOut
         * @description Copy that makes a checkable claim about the system, served rather than
         *     typed into each client (presentation/copy.py).
         */
        CopyOut: {
            /** Disclosures */
            disclosures: string[];
            /** Halt States */
            halt_states: components["schemas"]["HaltStateOut"][];
            /** Model Limits */
            model_limits: components["schemas"]["RuleOut"][];
            /** What This Is */
            what_this_is: string;
            /** Write Guards */
            write_guards: components["schemas"]["RuleOut"][];
            /** Write Guards Note */
            write_guards_note: string;
        };
        /** DecisionHorizonOut */
        DecisionHorizonOut: {
            /** Change */
            change: string | null;
            /** Direction Agreed */
            direction_agreed: boolean | null;
            /** Horizon */
            horizon: string;
            /** Observed Snapshot Id */
            observed_snapshot_id: string | null;
            /** Realized */
            realized: string | null;
            /** Resolved */
            resolved: boolean;
            /** Sessions */
            sessions: number;
            /** State */
            state: string;
            /** Underlying At Decision */
            underlying_at_decision: string | null;
            /** Underlying At Horizon */
            underlying_at_horizon: string | null;
        };
        /** DecisionListItem */
        DecisionListItem: {
            /** Action */
            action: string;
            /** Decided At */
            decided_at: string | null;
            /** Decision Id */
            decision_id: string;
            /** Direction */
            direction: string;
            /** Policy Version */
            policy_version: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** DecisionListOut */
        DecisionListOut: {
            /** Entries */
            entries: components["schemas"]["ListEntryOut"][];
            /** Grouped */
            grouped: boolean;
            /** Pin Missing */
            pin_missing: boolean;
            /** Shown */
            shown: number;
            /** Total */
            total: number;
            /**
             * View
             * @enum {string}
             */
            view: "Notable" | "Positions" | "Refusals" | "Everything";
        };
        /** DecisionPage */
        DecisionPage: {
            /** Items */
            items: components["schemas"]["DecisionListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** DecisionSummary */
        DecisionSummary: {
            /** Action */
            action: string;
            /** Decided At */
            decided_at: string | null;
            /** Decision Hash */
            decision_hash: string;
            /** Decision Id */
            decision_id: string;
            /** Direction */
            direction: string;
            /** Input Hash */
            input_hash: string;
            /** Model Was Called */
            model_was_called: boolean;
            observation: components["schemas"]["Observation"] | null;
            /** Policy Version */
            policy_version: string;
            /** Reached The Broker */
            reached_the_broker: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Snapshot Id */
            snapshot_id: string;
            /** Why */
            why: components["schemas"]["ExplainLineOut"][];
        };
        /** Envelope[ActivityPage] */
        Envelope_ActivityPage_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["ActivityPage"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[CopyOut] */
        Envelope_CopyOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["CopyOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[DecisionListOut] */
        Envelope_DecisionListOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["DecisionListOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[DecisionPage] */
        Envelope_DecisionPage_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["DecisionPage"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[DecisionSummary] */
        Envelope_DecisionSummary_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["DecisionSummary"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[LifecycleOut] */
        Envelope_LifecycleOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["LifecycleOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[MarketOut] */
        Envelope_MarketOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["MarketOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[MemoOut] */
        Envelope_MemoOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["MemoOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[ProofOut] */
        Envelope_ProofOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["ProofOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[ReviewOverviewOut] */
        Envelope_ReviewOverviewOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["ReviewOverviewOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[RiskOut] */
        Envelope_RiskOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["RiskOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[StructureOut] */
        Envelope_StructureOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["StructureOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[WorkerEventsOut] */
        Envelope_WorkerEventsOut_: {
            /** Correlation Id */
            correlation_id?: string | null;
            data: components["schemas"]["WorkerEventsOut"];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[list[DecisionHorizonOut]] */
        Envelope_list_DecisionHorizonOut__: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Data */
            data: components["schemas"]["DecisionHorizonOut"][];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[list[IncidentOut]] */
        Envelope_list_IncidentOut__: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Data */
            data: components["schemas"]["IncidentOut"][];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[list[ProofTileOut]] */
        Envelope_list_ProofTileOut__: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Data */
            data: components["schemas"]["ProofTileOut"][];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[list[SceneOut]] */
        Envelope_list_SceneOut__: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Data */
            data: components["schemas"]["SceneOut"][];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** Envelope[list[StatusItemOut]] */
        Envelope_list_StatusItemOut__: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Data */
            data: components["schemas"]["StatusItemOut"][];
            /** Observed At */
            observed_at: string;
            /**
             * Schema Version
             * @default public.v1
             * @constant
             */
            schema_version: "public.v1";
            /** Source Label */
            source_label: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "LIVE" | "FROZEN_REPLAY";
        };
        /** ExitOut */
        ExitOut: {
            /** Decided At */
            decided_at: string | null;
            /** Disposition */
            disposition: string | null;
            /** Invalidation Unverifiable */
            invalidation_unverifiable: boolean;
            /** Policy Version */
            policy_version: string;
            /** Reason */
            reason: string;
            /** Should Close */
            should_close: boolean;
            /** Suggested Limit */
            suggested_limit: string | null;
            /** Trigger */
            trigger: string;
            /** Unrealized */
            unrealized: string | null;
            /** Value Unmeasurable */
            value_unmeasurable: boolean;
        };
        /** ExplainLineOut */
        ExplainLineOut: {
            /** Present */
            present: boolean;
            /** Source */
            source: string;
            /** Stage */
            stage: string;
            /** Text */
            text: string;
        };
        /** FillOut */
        FillOut: {
            /** Filled At */
            filled_at: string | null;
            /** Leg Symbol */
            leg_symbol: string;
            /** Price */
            price: string | null;
            /** Quantity */
            quantity: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HaltStateOut */
        HaltStateOut: {
            /** Explanation */
            explanation: string;
            /** State */
            state: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "ok" | "warn" | "bad";
        };
        /**
         * HorizonCountsOut
         * @description Counts only. There is no rate field, and that is deliberate: over a corpus
         *     where every row is unanswerable, a rate would be a sentence about nothing.
         */
        HorizonCountsOut: {
            /** Agreed */
            agreed: number;
            /** Disagreed */
            disagreed: number;
            /** Horizon */
            horizon: string;
            /** Largest Move */
            largest_move: string | null;
            /** Pending */
            pending: number;
            /** Refusals */
            refusals: number;
            /** Resolved */
            resolved: number;
            /** Sessions */
            sessions: number;
            /** Smallest Move */
            smallest_move: string | null;
            /** Trades */
            trades: number;
            /** Unanswerable */
            unanswerable: number;
            /** With Realized */
            with_realized: number;
        };
        /** IncidentOut */
        IncidentOut: {
            /** Execution State */
            execution_state: string | null;
            /** Kind */
            kind: string;
            /** Open */
            open: boolean;
            /** Opened At */
            opened_at: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Severity */
            severity: string;
            /** Withheld */
            withheld: string[];
        };
        /** IntentOut */
        IntentOut: {
            /** Approval Reference */
            approval_reference: string | null;
            /** Client Order Id */
            client_order_id: string;
            /** Desired Limit Price */
            desired_limit_price: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Intent Hash */
            intent_hash: string;
            /** Legs */
            legs: {
                [key: string]: string | number | boolean | null;
            }[];
            /** Requests */
            requests: components["schemas"]["RequestOut"][];
        };
        /** LifecycleOut */
        LifecycleOut: {
            ablation: components["schemas"]["ArtifactOut"];
            /** Exits */
            exits: components["schemas"]["ExitOut"][];
            /** Intents */
            intents: components["schemas"]["IntentOut"][];
            /** Orders */
            orders: components["schemas"]["OrderOut"][];
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Reached The Broker */
            reached_the_broker: boolean;
            receipt: components["schemas"]["ArtifactOut"];
            trail: components["schemas"]["TrailOut"];
        };
        /** ListEntryOut */
        ListEntryOut: {
            /** Action */
            action: string;
            /** Count */
            count: number;
            /** Decision Id */
            decision_id: string;
            /** Direction */
            direction: string;
            /** Label */
            label: string;
            /** Member Ids */
            member_ids: string[];
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** MarketOut */
        MarketOut: {
            observation: components["schemas"]["Observation"] | null;
            /**
             * Observation Kind
             * @enum {string}
             */
            observation_kind: "fixture" | "provider" | "unavailable";
            qualification: components["schemas"]["QualificationOut"] | null;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
            structure?: components["schemas"]["StructureReadingOut"] | null;
        };
        /**
         * MemoOut
         * @description Separate from structure on purpose: the memo is the model's, advisory,
         *     and sizes nothing; structure is deterministic. One payload holding both
         *     would blur the authority line the product is built to draw.
         */
        MemoOut: {
            model_call: components["schemas"]["ModelCallOut"] | null;
            /** Produced */
            produced: boolean;
            thesis: components["schemas"]["ThesisOut"] | null;
        };
        /** ModelCallOut */
        ModelCallOut: {
            /** Input Hash */
            input_hash: string;
            /** Input Tokens */
            input_tokens: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Model */
            model: string;
            /** Output Schema Version */
            output_schema_version: string;
            /** Output Tokens */
            output_tokens: number | null;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Reasoning Effort */
            reasoning_effort: string | null;
            /** Status */
            status: string;
        };
        /** Observation */
        Observation: {
            /** Feed */
            feed: string;
            /** Payload Hash */
            payload_hash: string;
            /** Provider */
            provider: string;
            /** Received Time */
            received_time: string | null;
            /** Source Time */
            source_time: string | null;
            /** Symbol */
            symbol: string;
            /** Underlying Price */
            underlying_price: string | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Client Order Id */
            client_order_id: string;
            /** Deadline At */
            deadline_at: string | null;
            /** Filled Avg Price */
            filled_avg_price: string | null;
            /** Filled Quantity */
            filled_quantity: number | null;
            /** Fills */
            fills: components["schemas"]["FillOut"][];
            /** Local State */
            local_state: string | null;
            /** Prepared At */
            prepared_at: string | null;
            /** Reconciled At */
            reconciled_at: string | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Strategy Quantity */
            strategy_quantity: number | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Terminal */
            terminal: boolean;
            /** Withheld */
            withheld: string[];
        };
        /** PositionOut */
        PositionOut: {
            /** Avg Entry Debit */
            avg_entry_debit: string | null;
            /** Close Reason */
            close_reason: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Direction */
            direction: string;
            /** Entry Filled At */
            entry_filled_at: string | null;
            /** Expiration */
            expiration: string | null;
            /** Filled Quantity */
            filled_quantity: number | null;
            /** Invalidation Direction */
            invalidation_direction: string | null;
            /** Invalidation Level */
            invalidation_level: string | null;
            /** Invalidation Source */
            invalidation_source: string | null;
            /** Lifecycle Status */
            lifecycle_status: string;
            /** Long Symbol */
            long_symbol: string;
            /** Open Risk */
            open_risk: string | null;
            /** Opened At */
            opened_at: string | null;
            /** Requested Quantity */
            requested_quantity: number | null;
            /** Short Symbol */
            short_symbol: string;
            /** Strategy */
            strategy: string;
            /** Width */
            width: string | null;
        };
        /** ProofOut */
        ProofOut: {
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Manifest Digest */
            manifest_digest: string;
        };
        /** ProofTileOut */
        ProofTileOut: {
            /** Available */
            available: boolean;
            /** Detail */
            detail: string;
            /** Label */
            label: string;
            /** Mode */
            mode: string;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /** QualificationOut */
        QualificationOut: {
            /** Classifier Name */
            classifier_name: string;
            /** Direction */
            direction: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Invalidation Conditions */
            invalidation_conditions: string[];
            /** Payload Hash */
            payload_hash: string;
            /** Setup Family */
            setup_family: string;
            /** Setup Id */
            setup_id: string;
        };
        /** RequestOut */
        RequestOut: {
            /** Adapter Version */
            adapter_version: string;
            /** Dry Run Result */
            dry_run_result: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Intent Hash Match */
            intent_hash_match: boolean;
            /** Prepared At */
            prepared_at: string | null;
            /** Request */
            request: {
                [key: string]: unknown;
            };
            /** Request Hash */
            request_hash: string;
            /** Request Schema Version */
            request_schema_version: string;
            /** Withheld */
            withheld: string[];
        };
        /** ReviewOverviewOut */
        ReviewOverviewOut: {
            /** Caveat */
            caveat: string;
            /** Closes Observed */
            closes_observed: number;
            /** Decisions */
            decisions: number;
            /** Decisions Reviewed */
            decisions_reviewed: number;
            /** Horizons */
            horizons: components["schemas"]["HorizonCountsOut"][];
            /** Pending */
            pending: number;
            /** Positions Ever */
            positions_ever: number;
            /** Resolved */
            resolved: number;
        };
        /** RiskDecisionOut */
        RiskDecisionOut: {
            /** Approved */
            approved: boolean;
            /** Calculated Max Loss */
            calculated_max_loss: string | null;
            /** Checks */
            checks: {
                [key: string]: string | number | boolean | null;
            }[];
            /** Governor Name */
            governor_name: string;
            /** Intent Ttl Seconds */
            intent_ttl_seconds: number | null;
            /** Policy Version */
            policy_version: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Risk Budget */
            risk_budget: string | null;
        };
        /** RiskOut */
        RiskOut: {
            accounting: components["schemas"]["AccountingOut"] | null;
            /** Decisions */
            decisions: components["schemas"]["RiskDecisionOut"][];
        };
        /** RuleOut */
        RuleOut: {
            /** Effect */
            effect: string;
            /** Name */
            name: string;
        };
        /** SceneOut */
        SceneOut: {
            /** Decision Id */
            decision_id: string | null;
            /** Narration */
            narration: string;
            /** Number */
            number: number;
            /** Snapshot Id */
            snapshot_id: string;
            /** Tab */
            tab: number;
            /** Title */
            title: string;
        };
        /** SignalOut */
        SignalOut: {
            /** As Of */
            as_of: string | null;
            /** Direction */
            direction: string;
            /** Family */
            family: string;
            /**
             * Role
             * @enum {string}
             */
            role: "cited" | "counter-evidence" | "observed, unused";
            /** Signal Id */
            signal_id: string;
            /** Source */
            source: string;
            /** Strength */
            strength: string | null;
            /** Summary */
            summary: string;
        };
        /** SpreadCandidateOut */
        SpreadCandidateOut: {
            /** Calculated Max Loss */
            calculated_max_loss: string | null;
            /** Candidate Id */
            candidate_id: string;
            /** Estimated Debit */
            estimated_debit: string | null;
            /** Leg Quotes */
            leg_quotes: {
                [key: string]: string | number | boolean | null;
            }[];
            /** Long Contract Symbol */
            long_contract_symbol: string;
            /** Quantity */
            quantity: number;
            /** Rejection Reasons */
            rejection_reasons: string[];
            /** Selected */
            selected: boolean;
            /** Short Contract Symbol */
            short_contract_symbol: string;
            /** Strategy */
            strategy: string;
        };
        /** StatusItemOut */
        StatusItemOut: {
            /** Known */
            known: boolean;
            /** Label */
            label: string;
            /** Observed At */
            observed_at: string | null;
            /** Reason */
            reason: string | null;
            /** Source */
            source: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "ok" | "warn" | "bad" | "off" | "unknown";
            /** Value */
            value: string;
        };
        /** StructureOut */
        StructureOut: {
            /** Candidates */
            candidates: components["schemas"]["SpreadCandidateOut"][];
            selected: components["schemas"]["SpreadCandidateOut"] | null;
        };
        /**
         * StructureReadingOut
         * @description What the structure gate computed, whether or not it produced a signal.
         *
         *     `CIIP-VAL-012`. Without it a refusal is a reason code with no arithmetic
         *     behind it, and 201 of them cannot be told apart.
         */
        StructureReadingOut: {
            /** Bars Considered */
            bars_considered: number;
            /** Bars Required */
            bars_required: number;
            /** Close Side */
            close_side: string | null;
            /** Fast Ema */
            fast_ema: string | null;
            /** Gate */
            gate: string;
            /** Last Close */
            last_close: string | null;
            /** Retest Touched */
            retest_touched: boolean | null;
            /** Separation */
            separation: string | null;
            /** Separation Shortfall */
            separation_shortfall: string | null;
            /** Slow Ema */
            slow_ema: string | null;
        };
        /** ThesisOut */
        ThesisOut: {
            /** Confidence */
            confidence: string | null;
            /** Counter Evidence Ids */
            counter_evidence_ids: string[];
            /** Direction */
            direction: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Invalidation Conditions */
            invalidation_conditions: string[];
            /** Reasoning Summary */
            reasoning_summary: string;
            /** Synthesizer Name */
            synthesizer_name: string;
        };
        /** TrailOut */
        TrailOut: {
            /** Complete */
            complete: boolean;
            /** Events */
            events: components["schemas"]["ActivityEventOut"][];
            /** Gaps */
            gaps: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerEventOut */
        WorkerEventOut: {
            /** Detail */
            detail: {
                [key: string]: string | number | boolean | null;
            };
            /** Event */
            event: string;
            /** Kind */
            kind: ("state" | "cadence" | "fault") | string;
            /** Occurred At */
            occurred_at: string | null;
            /** Withheld */
            withheld: string[];
        };
        /** WorkerEventsOut */
        WorkerEventsOut: {
            /** Available */
            available: boolean;
            /** Items */
            items: components["schemas"]["WorkerEventOut"][];
            /** Reason */
            reason: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    system_activity_api_v1_activity_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ActivityPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authority_copy_api_v1_copy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CopyOut_"];
                };
            };
        };
    };
    decisions_api_v1_decisions_get: {
        parameters: {
            query?: {
                action?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DecisionPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decisions_grouped_api_v1_decisions_grouped_get: {
        parameters: {
            query?: {
                view?: string;
                pin?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DecisionListOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_lifecycle_api_v1_decisions__digest__lifecycle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LifecycleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_market_api_v1_decisions__digest__market_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MarketOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_memo_api_v1_decisions__digest__memo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MemoOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_outcomes_api_v1_decisions__digest__outcomes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_DecisionHorizonOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_proof_api_v1_decisions__digest__proof_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProofOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_risk_api_v1_decisions__digest__risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RiskOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_structure_api_v1_decisions__digest__structure_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StructureOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_summary_api_v1_decisions__digest__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DecisionSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_IncidentOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_overview_api_v1_outcomes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ReviewOverviewOut_"];
                };
            };
        };
    };
    proof_file_api_v1_proof__digest__json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description decision_hash hex, no prefix */
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_proof_api_v1_system_proof_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ProofTileOut__"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_StatusItemOut__"];
                };
            };
        };
    };
    guided_tour_api_v1_tour_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_SceneOut__"];
                };
            };
        };
    };
    worker_events_api_v1_worker_events_get: {
        parameters: {
            query?: {
                limit?: number;
                faults_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WorkerEventsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
